curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldcode.js -o assets/foldcode.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldgutter.css -o assets/foldgutter.css
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/fold/foldgutter.js -o assets/foldgutter.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/mode/simple.js -o assets/simple.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/search/search.js -o assets/search.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/search/searchcursor.js -o assets/searchcursor.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/addon/wrap/hardwrap.js -o assets/hardwrap.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.css -o assets/codemirror.css
curl https://cdn.jsdelivr.net/npm/codemirror@5/lib/codemirror.js -o assets/codemirror.js
curl https://cdn.jsdelivr.net/npm/codemirror@5/mode/markdown/markdown.js -o assets/markdown.js
curl https://cdn.jsdelivr.net/gh/mickael-kerjean/codemirror-orgmode/orgmode-fold.js -o assets/orgmode-fold.js
curl https://cdn.jsdelivr.net/gh/mickael-kerjean/codemirror-orgmode/orgmode-mode.js -o assets/orgmode-mode.js
curl https://cdn.jsdelivr.net/npm/dropbox@9/dist/Dropbox-sdk.js -o assets/Dropbox-sdk.js
curl https://raw.githubusercontent.com/dropbox/dropbox-sdk-js/main/examples/javascript/utils.js -o assets/Dropbox-utils.js
